### ISSUE TITLE
support for controllers

### ISSUE THREAD

**Issue by chrisbutler** [VeliovGroup/Meteor-iron-router-protected#1]
Hey, amazingly useful package. I was wondering if it would be trivial to also support setting these properties on iron router controllers for brevity?

**Comment by dr-dimitru** [comment]
Thank you for your comment on this package.
Could you give an example usage, please?

**Comment by chrisbutler** [comment]
here's what i'd like to be able to do:

```
LocationController = RouteController.extend({
  protected: true
});

Router.route('locations', {
  name: 'locations',
  controller: 'LocationController'
});
```

**Comment by dr-dimitru** [comment]
I'll work around it on this week, thank you for suggestion

**Comment by dr-dimitru** [comment]
Oh... I see PR now, tested?

**Comment by dr-dimitru** [comment]
@chrisbutler published to Atmosphere with few changes, could you please test on your end?

**Comment by chrisbutler** [comment]
@dr-dimitru awesome, thank you! looks great on my end
